// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irdivcxggziwvdmfazxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZGl2Y3hnZ3ppd3ZkbWZhenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDUzMjIsImV4cCI6MjA1ODc4MTMyMn0.g2FZV9MnTnpOEbZp1E4rFNrZ_ynUW3uQIfLRy7GP9v0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);